version: '2'
services:
  redis:
    build:
      context: ./
      dockerfile: dockerfiles/redis/redis.docker
    restart: always
  nginx:
    build:
      context: ./
      dockerfile: dockerfiles/nginx.docker
    volumes:
      - './:/var/www'
    restart: always
    ports:
      - '8081:80'
    links:
      - php
  php:
    build:
      context: ./
      dockerfile: dockerfiles/php/php.docker
    volumes:
      - './:/var/www'
      - './storage/tmp:/tmp'
    restart: always
    links:
      - mysql
      - redis
      - soketi
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - PUSHER_HOST=soketi
      - PUSHER_PORT=6001
  scheduler:
    build:
      context: ./
      dockerfile: dockerfiles/scheduler/scheduler.docker
    volumes:
      - './:/var/www'
      - './storage/tmp:/tmp'
    restart: always
    links:
      - mysql
      - redis
      - soketi
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - PUSHER_HOST=soketi
      - PUSHER_PORT=6001
  soketi:
    build:
      context: ./
      dockerfile: dockerfiles/soketi.docker
    restart: always
    ports:
      - '6001:6001'
  mysql:
    build:
      context: ./
      dockerfile: dockerfiles/mysql.docker
    volumes:
      - 'mysql-data:/var/lib/mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=AdM1n2022_!
      - MYSQL_DATABASE=ecommerce
    ports:
      - '33069:3306'
volumes:
  mysql-data: null
